# Generated by Django 3.2.4 on 2021-06-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao_curta', models.TextField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagens/Y%/m%/d%')),
                ('slug', models.SlugField(unique=True)),
                ('preco_marketing', models.FloatField(default=0)),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipos', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Varicao',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
            ],
            bases=('produto.produto',),
        ),
    ]
